environment_variables: &environment_variables
  app_name: "ThePlatform: API"
  sendgrid_key_id: <%= ENV['SENDGRID_KEY_ID'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  frontend_public_url: <%= ENV['FRONTEND_URL_PUBLIC'] %>
  frontend_local_url: <%= ENV['FRONTEND_URL_LOCAL'] %>

dev_and_testing_defaults: &dev_and_testing_defaults
  app_name: "ThePlatform: API (Test)"

development:
  <<: *environment_variables
  <<: *dev_and_testing_defaults

test:
  <<: *environment_variables
  <<: *dev_and_testing_defaults
  app_name: "ThePlatform: API (Development)"

production:
  <<: *environment_variables
